[package]
name = "webciify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tapciify = { version="*", git="https://github.com/tapnisu/tapciify" }
image = "0.24.6"
actix-web = "4"
